name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t kritigandhi/spring-boot-hello-world:latest .
          docker login -u kritigandhi -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push kritigandhi/spring-boot-hello-world:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster spring
